---
# Installation du paquet apache sur le serveur node-routeur, utile pour héberger un site interne

- name: "Installation apache"
  hosts: node-routeur
  roles:
    - role: "apache"
      php_install: "yes"

# Installation du paquet iptables-persistent, utile pour nos règles pare-feu

- name: "Installation Iptables"
  hosts: node-routeur
  roles:
    - role: "iptables"

# Installation du paquet isc-dhcp-server, utile pour la mise en place du DHCP

- name: "Installation isc-dhcp-server"
  hosts: node-routeur
  roles:
   - role: "dhcp-server"
