---

# 1. Cette tâche permets d'installer postfix à l'aide du module apt
- name: "postfix installation"
  apt:
    name: "postfix"
    state: "present"

# 2. Cette tâche active le service postfix
- name: "postfix service activation"
  service:
    name: "postfix"
    state: "started"
    enabled: "yes"

# 3. Ajout du fichier de configuration
- name: "copie du fichier main.cf vers le répertoire /etc/postfix"
  copy:
    src: /home/user-ansible/.ansible/roles/postfix/tasks/main.cf
    dest: /etc/postfix/main.cf
    owner: root
    mode: '0644'

# 4. Ajout du fichier de configuration
- name: "copie du fichier sasl_pawwd vers le répertoire /etc/postfix"
  copy:
    src: /home/user-ansible/.ansible/roles/postfix/tasks/sasl_passwd
    dest: /etc/postfix/sasl_passwd
    owner: root
    mode: '0644'

# 5. Ajout du fichier de configuration
- name: "copie du fichier sasl_passwd.db vers le répertoire /etc/postfix"
  copy:
    src: /home/user-ansible/.ansible/roles/postfix/tasks/sasl_passwd.db
    dest: /etc/postfix/sasl_passwd.db
    owner: root
    mode: '0644'
